#!/usr/bin/env bash
#########################
#
# the source code for afewmore
#
#########################

# default value
SOURCE_DIR='/data/'
NUM_CP=2
DONE_CP=0
VERBOSE=false    
TEMP_DIR='./tempDir'
# function of usage
usage(){
    echo "Usage: afewmore [-hv] [-d dir] [-t dir] [-n num] instance-id"
}

# if using the option -v print the message
msg(){
    if $VERBOSE;then
         echo $@
    fi 
}

fatal(){
    echo $@ >&2
    usage 
    exit 1
}

# function display option to use
help(){
echo "     -d dir   Copy the contents of this data directory from the orignal source
	      instance to all the new instances.  If not specified, defaults
	      to /data.
     -t  dir  specify the target dir

     -h       Print a usage statement and exit.

     -n num   Create this many new instances.  If not specified, defaults to
	      10.

     -v       Be verbose."
}

# function to check the instance is valid or not
check_instance(){

    local re='^i-[0-9a-f]{17}$'
    if ! [[ $INSTANCE_ID =~ $re ]];then
        fatal "Invalid format of instance ID"
    fi

    local checkinfo=$(aws ec2 describe-instances --query Reservations[].Instances[].InstanceId[] --output text | grep "$INSTANCE_ID")
   # echo $checkinfo
    if [[ $checkinfo == '' ]];then
        fatal "instance is not exist"
    fi
}

# function to check the number is valid
check_num(){
    local re='^[1-9][0-9]+$'
    if ! [[ $NUM_CP =~ $re ]] ; then
        fatal "Error not a valid number"
    fi
}


#fetch information using the instance id

fetch_info(){
    msg "fetching information...."
    local fetch=`aws ec2 describe-instances --instance-ids $INSTANCE_ID --output text --query 'Reservations[].Instances[].{Public_Dns_Name:PublicDnsName,Image_Id:ImageId, Key_Name:KeyName,Public_Dns_Name:PublicDnsName, Group_Id:SecurityGroups[].GroupId, Instance_Type:InstanceType, AvailabilityZone:Placement.AvailabilityZone}'`
    read AVA_ZONE IMAGE_ID INSTANCE_TYPE KEY_NAME PUBLIC_DNS_NAME GROUP_ID<<< $(echo $fetch)
    GROUP_ID=$(echo $GROUP_ID | awk '{print $2}')
    msg "Source instance info:"
    msg "Image_Id: $IMAGE_ID Key_Name: $KEY_NAME"
    msg "Instance_Type: $INSTANCE_TYPE AvailabilityZone: $AVA_ZONE SecurityGropus: $GROUP_ID"

}

# create instance
create_instance(){
    msg "create instance...."
    local start_instance=$(aws ec2 run-instances --count $NUM_CP --image-id $IMAGE_ID --key-name $KEY_NAME --instance-type $INSTANCE_TYPE --placement AvailabilityZone="$AVA_ZONE" --security-group-ids $GROUP_ID --output json>test.txt)
    cat test.txt|grep InstanceId|awk '{print substr($2,2,19)}'
    INSTANCE_ID_LIST=($(cat test.txt|grep InstanceId|awk '{print substr($2,2,19)}'))
    local INDEX=0
    PUBLIC_DNS_LIST=()
    for id in "${INSTANCE_ID_LIST[@]}"
     do
        PUBLIC_DNS_LIST[$INDEX]=$(aws ec2 describe-instances --instance-ids $id --output text --query 'Reservations[].Instances[].{Public_Dns_Name:PublicDnsName}')
        #echo ${PUBLIC_DNS_LIST[$INDEX]}
        local INDEX=$INDEX+1
    done
}
#copy the target directory
#need to think about ubuntu, ec2-user, root
download_target_dir(){
    mkdir tempDir
    scp -o StrictHostKeyChecking=no -i ~/Downloads/key.pem -r ubuntu@$PUBLIC_DNS_NAME:$SOURCE_DIR $TEMP_DIR>/dev/null

}
#get the target dir from the path
get_dir_name(){
    DIR_NAME=$(basename $SOURCE_DIR)
}
#wait until all new created instances initialized done
wait_until_initialized(){
    for id in "${INSTANCE_ID_LIST[@]}"
        do
            local count=$(aws ec2 describe-instance-status --instance-ids $id|grep '"Status": "ok",'|wc -l)
            while [ $count -lt 2 ] 
            do
                count=$(aws ec2 describe-instance-status --instance-ids $id|grep '"Status": "ok",'|wc -l)
                sleep 10
            done
        done
}
#up load the data to all new instances
upload_target_dir(){
    for DNS in "${PUBLIC_DNS_LIST[@]}"
        do
            #echo ubuntu@$DNS:~/  
            scp -o StrictHostKeyChecking=no -i ~/Downloads/key.pem -r $TEMP_DIR/$DIR_NAME ubuntu@$DNS:~/>/dev/null
        done
}
#remove the  temporary directory
rm_temp_dir(){
    rm -rf $TEMP_DIR
}
# check staus 

check_status(){
    msg "checking status of instance: $@..."
    local res=$(aws ec2 describe-instance-status --instance-ids $@ --output text | awk ' $3~/passed/ {print}'| wc -l)
    msg "check: $res/2"
}

# main 
while true; do
	case $1 in
	    -h) help; exit 0 ;; 
	    -v) VERBOSE=true; shift ;;
        -d) shift; SOURCE_DIR=$1 ; shift ;;
        -t) shift; TARGET_DIR=$1 ; shift ;;
        -n) shift; NUM_CP=$1 ;check_num ; shift ;;
        -*) fatal "Invalid arguments : $1" ;;
        *) 
            if [[ $# -lt 1 ]]; then
                fatal "Please specify the instance id"
            else
                INSTANCE_ID=$1
                check_instance
                fetch_info
                create_instance
                download_target_dir
                get_dir_name 
                wait_until_initialized
                upload_target_dir
                rm_temp_dir
                check_status $INSTANCE_ID                
                exit 0       
            fi ;;
    esac
done
